apiVersion: v1
kind: Service
metadata: 
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: primeiro-pod
  ports:
    - port: 80
      # targetPort: 80 # Se n찾o for diferente da porta do pod, n찾o precisa ser informado
      nodePort: 30000 # Porta exposta externamente no n처 (opcional; Kubernetes pode atribuir automaticamente se n찾o especificado)