apiVersion: v1
kind: Pod
metadata: 
  name: screensound-api
  labels: 
    app: screensound-api
spec:
  containers:
    - name: screensound-api-container
      image: ricardochies/screensoundapi:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: configmap-screensound