apiVersion: v1
kind: Service
metadata: 
  name: svc-screensound
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080 # Realizei essa configuração no Dockerfile da API
      nodePort: 30000
  selector:
    app: screensound-api