apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-api-screensound
  labels: 
    app: api-screensound
spec:
  template: # Define o modelo para os pods gerenciados por este Deployment.
    metadata:
        name: api-screensound
        labels: 
          app: api-screensound
    spec:
      containers:
        - name: api-container-screensound
          image: ricardochies/screensoundapi:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap-api-screensound
          livenessProbe: # Define a verificação de vivacidade para o contêiner.
            httpGet:
              path: /swagger/index.html # Caminho HTTP que será utilizado para verificar se o contêiner está vivo.
              port: 8080 # Porta na qual a verificação será realizada.
            periodSeconds: 10 # Intervalo de tempo entre as verificações de vivacidade.
            failureThreshold: 3 # Número de falhas consecutivas antes de considerar o contêiner como não vivo.
            initialDelaySeconds: 20 # Tempo de espera antes de realizar a primeira verificação após o contêiner ser iniciado.
          readinessProbe: # Define a verificação de prontidão para o contêiner.
            httpGet:
              path: /swagger/index.html # Caminho HTTP que será utilizado para verificar se o contêiner está pronto para receber tráfego.
              port: 8080 # Porta na qual a verificação será realizada.
            periodSeconds: 10 # Intervalo de tempo entre as verificações de prontidão.
            failureThreshold: 5 # Número de falhas consecutivas antes de considerar o contêiner como não pronto.
            initialDelaySeconds: 3 # Tempo de espera antes de realizar a primeira verificação de prontidão após o contêiner ser iniciado.
          resources: # Define os requisitos de recursos para o contêiner.
            requests:
              cpu: 10m # Solicitação mínima de CPU que o contêiner precisa para ser agendado.
  replicas: 3 # Define o número de réplicas (pods) que devem ser executadas.
  selector:
    matchLabels:
      app: api-screensound