apiVersion: v1
kind: Pod
metadata: 
  name: api-screensound
  labels: 
    app: api-screensound
spec:
  containers:
    - name: api-container-screensound
      image: ricardochies/screensoundapi:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: configmap-api-screensound